In [1]:
import pandas as pd

In [13]:
df1 = pd.read_csv('twitter_ai.csv')
df2 = pd.read_csv('twitter_ds.csv')
df3 = pd.read_csv('twitter_kaggle.csv')
df4 = pd.read_csv('twitter_python.csv')

In [14]:
df1

,searched_for,post_url,post,user,post_time,hashtags,hashtag_len
0,#人工知能,https://twitter.com/benrishi1/status/125772625...,経営者が知るべき人工知能が生むビジネスチャンスを つかむための戦略とは？ \nhttps:/...,人工知能、機械学習、ＩｏＴニュース,1.588700e+09,機械学習 ai iot 人工知能,4
1,#人工知能,https://twitter.com/ciwame_mizuo/status/124367...,AIで風景を作る\niteration/epoch: 11000/2\n#makeingla...,みずお,NaN,makeinglandscape deeplearning nowlearning ai g...,6
2,#人工知能,https://twitter.com/sachi_n1020/status/1257695...,主婦だけど、何か仕事をしたいと思ってませんか？\nスマホ片手で在宅でできますよ〜\n#副業 ...,naru@相互フォロー,1.588693e+09,働き方改革 副業探しています 集客 インターネット 社会問題 環境問題 相互フォロー ai ...,11
3,#人工知能,https://twitter.com/JohnnyFakaHioki/status/124...,シンギュラリティ後の世界が明るく楽しいものなら、その日を待つためだけに25年生きてもいいな。...,草木の妖精-ジョニー・フローラ -Johnny Flora-,NaN,シンギュラリティ 人工知能,2
4,#人工知能,https://twitter.com/kawachanaccount/status/125...,AIは恋する #小説 #SF #人工知能 #プログラマー\nhttps://t.co/oQz...,KAWAMURA小説アカウント,1.588693e+09,小説 プログラマー sf 人工知能,4
...,...,...,...,...,...,...,...
6507,#人工知能,https://twitter.com/ciwame_mizuo/status/124368...,AIで風景を作る\niteration/epoch: 12000/2\n#makeingla...,みずお,NaN,makeinglandscape deeplearning nowlearning ai g...,6
6508,#人工知能,https://twitter.com/KyukyokuCom/status/1243682...,人工知能（AI）が米国、数百万人の職を奪う！「やりすぎ都市伝説で言ってた人類選別がはじまる？...,究極のまとめ.com,NaN,都市伝説 やりすぎ都市伝説 ai 人工知能,4
6509,#人工知能,https://twitter.com/InfoAI4/status/12436819956...,「なぜ」を理解するAIの構築を、あの人工知能の第一人者は目指している｜https://t.c...,Info_AI,NaN,ai 人工知能,2
6510,#人工知能,https://twitter.com/meza_janken/status/1243679...,【2戦目】めざましじゃんけん結果速報：\nチョキ✌でした。グー✊が勝ちです。\n今回の相手：...,めざましじゃんけん結果速報,NaN,めざましじゃんけん じゃんけん みきいえ ゆりやんレトリィバァ めざましどようび めざましテ...,9
6511,#人工知能,https://twitter.com/meza_janken/status/1243678...,学習中の人工知能なので、とても低い勝率です。\n次回3月28日 【2戦目】のじゃんけん予想は...,めざましじゃんけん結果速報,NaN,めざましじゃんけん じゃんけん opencv keras raspberrypi rnn め...,11

In [15]:
df2

,searched_for,post_url,post,user,post_time,hashtags,hashtag_len
0,#データサイエンティスト,https://twitter.com/K03475916/status/125781058...,#今日の積み上げ\n・Udemy中級編7.8\n・DS養成講座30回31回課題\n・prog...,K,1.588720e+09,筋トレ 今日の積み上げ 駆け出しエンジニアと繋がりたい データサイエンティスト,4
1,#データサイエンティスト,https://twitter.com/ponpoko_code/status/844690...,データ分析って給料高いな～。人材不足らしい。統計学、プログラミングに加えて人工知能も出来ると...,ぽんぽこ@プロぽこ-プログラミング,NaN,統計学 人工知能 ダイヤモンド データサイエンティスト プログラミング,5
2,#データサイエンティスト,https://twitter.com/sazan_dora/status/79743408...,データサイエンティストになりたい人向けまとめ - NAVER まとめ https://t.c...,サザンドラ,NaN,データマイニング データサイエンス データサイエンティスト,3
3,#データサイエンティスト,https://twitter.com/WXBC_jp/status/11302604362...,【#野球 ネタ⚾️】\n\n#ヤクルトスワローズ の #山田哲人 選手の成績データを、気温・...,"気象ビジネス推進コンソーシアム（略称：WXBC,事務局：気象庁）",NaN,山田哲人 気象 データサイエンティスト ヤクルトスワローズ,4
4,#データサイエンティスト,https://twitter.com/hamahiroshi164/status/1257...,「データサイエンティストを目指す人のzoom飲み会」終わりました💡\n\n現場のリアルが知れ...,DSになる男ハマヒロシ30歳子煩悩,1.588689e+09,プログラミング初心者 データサイエンティスト,2
...,...,...,...,...,...,...,...
1484,#データサイエンティスト,https://twitter.com/Iggjj21/status/12162382360...,#今日の積み上げ \n\n✔️PYQでpandasの演習\n→主に表の作成方法\n✔️cou...,ゆう|新社会人エンジニア,NaN,駆け出しエンジニア python 今日の積み上げ 機械学習 データサイエンティスト ai 駆...,7
1485,#データサイエンティスト,https://twitter.com/fumi_bz/status/10116001000...,Agile HR Day にて。そもそもいないデータサイエンティスト人材‥っていう、スライド...,fumi@HR Tech商品企画,NaN,機械学習 hrtech ディープラーニング データサイエンティスト,4
1486,#データサイエンティスト,https://twitter.com/joe_i/status/1794720198705...,#データサイエンティスト 不足の問題は昨日も話題に上がってましたが、本当にそうですよねー。昨...,石山 城 / Joe ISHIYAMA,NaN,データサイエンティスト opencu,2
1487,#データサイエンティスト,https://twitter.com/intern_aogaku/status/79775...,統計学を学ぶ学生必見！\n\nIoT企業でデータサイエンティストの有給インターンシップ募集！...,青山学院大学 インターン就活おすすめ情報,NaN,インターンシップ インターン マーケティング データサイエンス データサイエンティスト 統計...,7
1488,#データサイエンティスト,https://twitter.com/shibaurakogyo_u/status/797...,統計学を学ぶ学生必見！\n\nIoT企業でデータサイエンティストの有給インターンシップ募集！...,芝浦工業大学 インターン就活おすすめ情報,NaN,インターンシップ インターン マーケティング データサイエンス データサイエンティスト 統計...,7

In [16]:
df3

,searched_for,post_url,post,user,post_time,hashtags,hashtag_len
0,#kaggle,https://twitter.com/AbeShumpei/status/11002246...,はじめて出して見た。8000番と順位は低いけどこれからがんばるぞいDoing my part...,abe shumpei,NaN,kaggle machinelearning,2
1,#kaggle,https://twitter.com/soh_1121_/status/125767813...,◯ 実施内容\n・ #Paiza 1h\n・ #言語処理100本ノック 0.5h\n・ #K...,Soh,1.588689e+09,言語処理100本ノック apg4b 個人開発 kaggle 今日の積み上げ 駆け出しエンジニ...,9
2,#kaggle,https://twitter.com/WlWH74jtP0zHxmj/status/125...,AIの目標はやっぱりKaggleかな\nグランドマスターとか憧れすぎる\nいろいろ挑戦してみ...,やますん@駆け出しエンジニア,1.588677e+09,プログラミング学習 ai kaggle,3
3,#kaggle,https://twitter.com/bonjinjpn/status/110005131...,#SIGNATE - Data Science Competition #ML #DL #A...,K2,NaN,dl signate kaggle ai ml,5
4,#kaggle,https://twitter.com/tkydub/status/109950639977...,届きました🙌 #kaggle #機械学習 #機械学習のための特徴量エンジニアリング,toki⛅,NaN,kaggle 機械学習のための特徴量エンジニアリング 機械学習,3
...,...,...,...,...,...,...,...
1219,#kaggle,https://twitter.com/Wataoka_Koki/status/110109...,kaggle二日目\n\nDNNのkernelを自分好みにアレンジしながら実装した。\n\n...,綿岡 晃輝,NaN,santander kaggle,2
1220,#kaggle,https://twitter.com/codexa_net/status/11010897...,【Kaggle初心者入門編】タイタニック号で生き残るのは誰？\n\n#Kaggle #入門\...,codexa[コデクサ:人工知能特化WEBスクール],NaN,入門 kaggle,2
1221,#kaggle,https://twitter.com/hntk03/status/110099597289...,Feature Engineering #featureengineering #kaggl...,hntk,NaN,featureengineering kaggle,2
1222,#kaggle,https://twitter.com/sa178kla/status/1100890178...,"もっと頑張ろうー\nCausing #superintelligence, one subm...",yo,NaN,superintelligence kaggle,2
1223,#kaggle,https://twitter.com/dichika/status/29512284824...,適当にgbmにつっこんだら0.76555で924位ダッタヨ #kaggle #titanic,棗太郎,NaN,titanic kaggle,2

In [17]:
df4

,searched_for,post_url,post,user,post_time,hashtags,hashtag_len
0,#python,https://twitter.com/joekadowaki/status/1245109...,｢仕事のムダ｣を省くための、コミュニケーションに関する2つのポイント\nhttps://t....,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3
1,#python,https://twitter.com/maronaru_sale_t/status/125...,LINEの半bot、保護botのソースや\nPythonista3の使い方\nソースの書き方...,U&I iryuSale LINEbot販売,1.588720e+09,半bot プログラミング pythonista 保護bot linebot python p...,8
2,#python,https://twitter.com/joekadowaki/status/1245108...,「ビジネスメール詐欺の実態調査報告書」を公開 JPCERT/CC\nhttps://t.co...,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3
3,#python,https://twitter.com/sheep_0411/status/12578075...,"日経平均\n2020年05月01日の終値：19,619.35円\n(前日比-2.84%)\n...",シープ,1.588720e+09,heroku bot python 日経平均,4
4,#python,https://twitter.com/joekadowaki/status/1245108...,ライス大学研究チーム、GPUを使わずにディープラーニングを高速化するアルゴリズムを開発\nh...,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3
...,...,...,...,...,...,...,...
5270,#python,https://twitter.com/Kuno39962216/status/124511...,2020年4月1日学習\n・Udemy 【世界で5万人が受講】実践 Pythonデータサイエ...,kuno&pandapi,NaN,udemy python データサイエンス,3
5271,#python,https://twitter.com/BASEBALLY15/status/1245109...,#今日の積み上げ\n今日も頑張りましょう😊\n\n▶️ #Python ブログ執筆\n▶️ ...,ゆうき@Python＋C💻ブログで発信📝,NaN,今日の積み上げ python 駆け出しエンジニアと繋がりたい,3
5272,#python,https://twitter.com/joekadowaki/status/1245109...,リモートワークで疲弊する人へ｜この際、生産性は忘れよう\nhttps://t.co/mJnU...,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3
5273,#python,https://twitter.com/joekadowaki/status/1245109...,地頭のいい人≠アイデアマン。｢問題解決｣への最短距離のつくり方\nhttps://t.co/...,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3
5274,#python,https://twitter.com/joekadowaki/status/1245109...,オンライン会議を生かす、スムーズな進め方と注意点\nhttps://t.co/w88CTnb...,じょー,NaN,python technology 駆け出しエンジニアと繋がりたい,3

In [23]:
cols = ['searched_for', 'hashtags', 'hashtag_len']
df1 = df1[cols]
df2 = df2[cols]
df3 = df3[cols]
df4 = df4[cols]

In [24]:
df = pd.concat([df1, df2], axis=0)
df = pd.concat([df, df3], axis=0)
df = pd.concat([df, df4], axis=0)

In [28]:
df.sample(100)

,searched_for,hashtags,hashtag_len
5643,#人工知能,トルコ ドローン 神風ドローン 顔認証 ai drone 人工知能,7
2944,#python,駆け出しエンジニアとつながりたい python プログラミング初心者,3
210,#kaggle,kaggle 機械学習 データサイエンティスト,3
2115,#python,駆け出しエンジニアと繋がりたい プログラミング python プログラミング学習 プログラミ...,5
1275,#データサイエンティスト,統計学 統計学専攻 データサイエンティスト 統計 外資系 外資系企業,6
...,...,...,...
1666,#python,python 機械学習 回帰分析,3
6165,#人工知能,makeinglandscape deeplearning nowlearning ai g...,6
5210,#python,オホーツク fswebcam python イマソラ 北海道 photo raspberrypi,7
873,#人工知能,ai 人工知能,2
3881,#人工知能,セルフブランディング ai ルーチンワーク 人工知能,4

In [26]:
df.to_csv('twitter_post.csv', index=False)